### PR TITLE
Code and documentation to support looping

### PR DESCRIPTION
**Pull request by wintondeshong**
I've added the ability for the stack to optionally loop when the user attempts to navigate to either bound of the stack. The default behavior will remain the same where `loop: false`. I also added the defaults to the readme markdown file. Please review and let me know if you have any comments. Thanks!

### CODE REVIEW

**Comment by Jcrawford19** [comment]
+1, thanks for adding this

**Comment by sshearer-rsm** [comment]
+1

**Comment by phess101** [comment]
+1

**Comment by nicolasmure** [comment]
+1 great! :smile:

**Comment by wintondeshong** [comment]
I've caught an issue with the animations in the looping. I'll let you know when it has been resolved.

**Comment by wintondeshong** [comment]
Alright, animation issues have been resolved. Ready for review!

**Comment by mbsathik** [comment]
is there any default options for autostart? with out navigating right or left arrow

**Pull request closed without merging**
